config/routes.rb
Rails.application.routes.draw do
  root :to => 'questions#index'

  resources :users do
    resources :questions
  end
  resources :sessions

  resources :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :content, :votes, :user_id, :presence => true
  belongs_to :user

  after_initialize :init

  def init
    self.votes ||= 0.0
  end
end

app/models/session.rb
class Session < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :questions

  validates :email, :password_digest, :presence => true

  validates_uniqueness_of :email



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to new_session_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authorize, only: [:new, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @user = User.find(current_user.id)
    @question = @user.questions.new
  end

  def create
    @user = User.find(current_user.id)
    @question = @user.questions.new(question_params)
    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def edit
    @user = User.find(current_user.id)
    @question = @user.questions.find(params[:id])
  end

  def update
    @user = User.find(current_user.id)
    @question = @user.questions.find(params[:id])
    if @question.update(question_params)
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

private
  def question_params
    params.require(:question).permit(:title, :content, :votes, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged In!"
    else
      redirect_to new_session_path, alert: "Email or password is invalid"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render :new
    end
  end

private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div id="user_header">
        <% if current_user %>
          Logged in as <%= current_user.email %>.
          <%= link_to "log out", session_path("current"), method: "delete" %>
        <% else %>
          <%= link_to "sign up", new_user_path %> or
          <%= link_to "log in", new_session_path %>
        <% end %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for [@user, @question] do |f| %>

<% if @question.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_area :content%>
  <%= f.hidden_field(:user_id, :value => @user.id) %>
  <%= f.submit %>
<% end %>

<p> <%= link_to "Return to questions", questions_path  %></p>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<h1> (The real) STACK OVERFLOW</h1>

  <ul>
    <% @questions.each do |question| %>
      <li>
        <h3><%= link_to question.title, question_path(question) %></h3>
        <p><%= question.content %></p>
      </li>
    <% end %>
  </ul>

<p> <%= link_to "Ask a new question", new_question_path  %></p>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<h3><%= @question.content %></h3>

<p> <%= link_to "Edit Question", edit_question_path  %></p>
<p><%= link_to "Delete Question", question_path(@question), :data => {:confirm => "Are you sure you want to delete this question?", :method => "delete"} %></p>

app/views/users/index.html.erb
<h1>Users Index!</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %> <br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %> <br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %> <br>
    <%= f.password_field :password_confirmation %>
    <%= f.submit %>
  </div>
<% end %>